wdinstagram_app/config/routes.rb
Rails.application.routes.draw do
  resources :entries
  root 'entries#index'

end

wdinstagram_app/app/models/entry.rb
class Entry < ActiveRecord::Base
end

wdinstagram_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

wdinstagram_app/app/controllers/entries_controller.rb
class EntriesController < ApplicationController
	def index
		@entries = Entry.all
	end

	def show
		@entry = Entry.find(params[:id])
	end

	def new
		@entry = Entry.new
	end

	def create
		
	end

	def edit
		@entry = Entry.find(params[:id])
	end

	def update
	end

	def destroy
		@movie.destroy
	end
end

wdinstagram_app/app/helpers/application_helper.rb
module ApplicationHelper
end

wdinstagram_app/app/helpers/entry_helper.rb
module EntryHelper
end

wdinstagram_app/app/views/entries/index.html.erb
<% @entries.each do |entry| %>
<%= entry.author %>
<%= entry.photo_url %>
<% end %>


<br>
<%= link_to "New Entry", new_entry_path %>

wdinstagram_app/app/views/entries/new.html.erb
<%= form_for (@entry) do |f| %>
<%= f.label :author %>
<%= f.text_field :author %><br>
<%= f.label :photo_url %>
<%= f.text_field :photo_url %><br>
<%= f.submit %>
<% end %>

wdinstagram_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WdinstagramApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>